[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fmt]
line_length = 120
single_line_statement_blocks = "multi"

runs = 1024
max_test_rejects = 16777216

# See more config options https://github.com/foundry-rs/foundry/tree/master/config